BookEventManager.UserInterface/Controllers/EventCommentsController.cs
using BookEventManager.Business.Logic;
using BookEventManager.Shared.DTO;
using System.Net;
using System.Web.Mvc;

namespace BookEventManager.UserInterface.Controllers
{
    public class EventCommentsController : Controller
    {
        private IReadData readObj;
        private IWriteData writeObj;

        public EventCommentsController(IWriteData writeObj, IReadData readObj)
        {
            this.writeObj = writeObj;
            this.readObj = readObj;
        }
        // GET: EventComments
        /*public ActionResult Index()
        {
            return View(db.Comments.ToList());
        }*/

        // GET: EventComments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var eventComment = readObj.FetchCommentsOfEvent(id);

            if (eventComment == null)
            {
                return HttpNotFound();
            }
            return View(eventComment);
        }

        // GET: EventComments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EventComments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommentId,Comment,UserId,Email,FullName,EventId,CurrentDate")] EventCommentDTO eventComment)
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                eventComment.UserId = readObj.GetUserIdByEmail(User.Identity.Name);
                eventComment.Email = readObj.GetUserEmail(eventComment.UserId);
                eventComment.FullName = readObj.GetUserFullName(eventComment.UserId);

                writeObj.AddComment(eventComment);
                return View();
            }
            ModelState.AddModelError("", "You are not Logged in!!!");
            return View();
        }

        // GET: EventComments/Edit/5
        /*public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventComment eventComment = db.Comments.Find(id);
            if (eventComment == null)
            {
                return HttpNotFound();
            }
            return View(eventComment);
        }

        // POST: EventComments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommentId,Comment,UserId,EventId,CurrentDate")] EventComment eventComment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventComment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eventComment);
        }*/

        // GET: EventComments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventCommentDTO eventComment = readObj.GetCommentWithCommentId(id);
            if (eventComment == null)
            {
                return HttpNotFound();
            }
            return View(eventComment);
        }

        // POST: EventComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventCommentDTO eventComment = readObj.GetCommentWithCommentId(id);
            writeObj.DeleteComment(eventComment);
            return RedirectToAction("Details", "Events", new { id = eventComment.EventId });
        }

        /*protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

BookEventManager.UserInterface/Controllers/EventsController.cs
using BookEventManager.Business.Logic;
using BookEventManager.Shared.DTO;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace BookEventManager.UserInterface.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private IReadData readObj;
        private IWriteData writeObj;

        public EventsController(IWriteData writeObj, IReadData readObj)
        {
            this.writeObj = writeObj;
            this.readObj = readObj;
        }
        // GET: Events
        public ActionResult Index()
        {
            var UID = readObj.GetUserIdByEmail(User.Identity.Name);
            var events = readObj.FetchMyEvents(UID);
            return View(events);
        }
        public ActionResult InvitedTo()
        {
            if (User.Identity.IsAuthenticated)
            {
                IEnumerable<EventDTO> events = readObj.FetchEventsInvitedTo(User.Identity.Name);
                return View(events);
            }
            return RedirectToAction("Login", "User");
        }

        // GET: Events/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventDTO @event = readObj.FetchEventDetails(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                List<string> timeList = new List<string>();
                for (int i = 0; i < 24; i++)
                {
                    if (i < 10)
                        timeList.Add("0" + i + ":00");
                    else
                        timeList.Add(i + ":00");
                }
                ViewBag.List = timeList;

                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventId,UserId,UserEmail,UserFullName,Title,DateOfEvent,StartTime,Location,Type,Duration,Description,OtherDetails,CountOfInvitedTo,InvitedTo,EventCreateDateTime")] EventDTO @event)
        {
            if (ModelState.IsValid)
            {
                //if (@event.Duration > 0 && @event.Duration < 5)
                //{
                if(@event.Type == null)
                {
                    @event.Type = true;
                }
                    int UID = readObj.GetUserIdByEmail(User.Identity.Name);
                    @event.UserId = UID;
                    string email = readObj.GetUserEmail(UID);
                    @event.UserEmail = email;
                    string name = readObj.GetUserFullName(UID);
                    @event.UserFullName = name;
                    int countOfInvitedTo = readObj.GetInvitedToEmailCount(@event.InvitedTo);
                    @event.CountOfInvitedTo = countOfInvitedTo;
                    writeObj.CreateEvent(@event);
                    return RedirectToAction("Index");
               }
                //else
                //{
                    //ModelState.AddModelError("", "Duration should lie between 1 and 4");
                //}
            //}
            List<string> timeList = new List<string>();
            for (int i = 0; i < 24; i++)
            {
                if (i < 10)
                    timeList.Add("0" + i + ":00");
                else
                    timeList.Add(i + ":00");
            }
            ViewBag.List = timeList;

            return View(@event);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (User.Identity.IsAuthenticated)
            {
                EventDTO @event = readObj.FetchEventDetails(id);
                if (@event == null)
                {
                    return HttpNotFound();
                }
                List<string> timeList = new List<string>();
                for (int i = 0; i < 24; i++)
                {
                    if (i < 10)
                        timeList.Add("0" + i + ":00");
                    else
                        timeList.Add(i + ":00");
                }
                ViewBag.List = timeList;
                return View(@event);
            }
            return RedirectToAction("Login", "User");
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventId,UserId,UserEmail,UserFullName,Title,DateOfEvent,StartTime,Location,Type,Duration,Description,OtherDetails,InvitedTo,EventCreateDateTime")] EventDTO @event)
        {
            if (ModelState.IsValid)
            {
                var UID = readObj.GetUserIdByEventId(@event.EventId);
                @event.UserId = UID;
                string email = readObj.GetUserEmail(UID);
                @event.UserEmail = email;
                string name = readObj.GetUserFullName(UID);
                @event.UserFullName = name;
                writeObj.EditEvent(@event);
                
                if (User.Identity.Name.Equals("myadmin@bookevents.com"))
                {
                    return RedirectToAction("Index", "Home");
                }
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (User.Identity.IsAuthenticated)
            {
                EventDTO @event = readObj.FetchEventDetails(id);
                if (@event == null)
                {
                    return HttpNotFound();
                }
                return View(@event);
            }
            return RedirectToAction("Login", "User");
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            writeObj.DeleteEvent(id);
            if(User.Identity.Name.Equals("myadmin@bookevents.com"))
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index");
        }

        /*protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

BookEventManager.UserInterface/Views/Events/Create.cshtml
@model BookEventManager.Shared.DTO.EventDTO

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />

        <div class="form-group">

            @Html.Label("Event Title*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Event Date*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfEvent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfEvent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Start Time*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StartTime",
                    new SelectList(ViewBag.list),
                    "Select start Time",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.Label("Event Location*", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Event Type", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Type)
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                        @Html.Label("Public(True, Default)/Private(False)", htmlAttributes: new { @class = "control-label" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Event Duration(Hr)", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Other Details(if any)", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OtherDetails, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OtherDetails, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.InvitedTo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.InvitedTo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.InvitedTo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookEventManager.UserInterface/Views/Events/Delete.cshtml
@model BookEventManager.Shared.DTO.EventDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Email Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserEmail)
        </dd>

        <dt>
            @Html.Label("Created By")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserFullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfEvent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfEvent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @if (Model.Type == true)
            {
                @Html.Label("Public");
            }
            else
            {
                @Html.Label("Private");
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OtherDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OtherDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvitedTo)
        </dt>

        <dd>
            @if (Model.InvitedTo != null)
            {
                foreach (var e in Model.InvitedTo.Split(','))
                {
                    <label>@e</label><br />
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventCreateDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventCreateDateTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Home", "Index", "Home")
</div>
    }
</div>

BookEventManager.UserInterface/Views/Events/Details.cshtml
@model BookEventManager.Shared.DTO.EventDTO

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Email Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserEmail)
        </dd>

        <dt>
            @Html.Label("Created By")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserFullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfEvent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfEvent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @if (Model.Type == true)
            {
                @Html.Label("Public");
            }
            else
            {
                @Html.Label("Private");
            }
        </dd>


        @if (Model.Duration > 0)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Duration)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Duration)
            </dd>
        }

        @if (Model.Description != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        }

        @if (Model.OtherDetails != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.OtherDetails)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OtherDetails)
            </dd>
        }

        <dt>
            @Html.Label("Count Of Invited To ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountOfInvitedTo)
        </dd>

        <dt>
            @Html.Label("Invited To ")
        </dt>

        <dd>
            @if (Model.InvitedTo != null)
            {
                foreach (var e in Model.InvitedTo.Split(','))
                {
                    <label>@e</label><br />
                }
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back", null, null, null, new { href = Request.UrlReferrer })
    @if (User.Identity.Name.Equals("myadmin@bookevents.com"))
    {
        @Html.ActionLink("| Delete", "Delete", "Events", null, new { id = Model.EventId })
    }
</p>

<div>
    @{
        Html.RenderAction("Create", "EventComments", new { EventId = Model.EventId });
    }
</div>

<div>
    @{
        Html.RenderAction("Details", "EventComments", new { EventId = Model.EventId });
    }
</div>

BookEventManager.UserInterface/Views/Events/Edit.cshtml
@model BookEventManager.Shared.DTO.EventDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Event</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventId)


        <div class="form-group">
            @Html.Label("Event Title*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Event Date*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfEvent, new { htmlAttributes = new { @class = "form-control datepicker", @Value = Model.DateOfEvent.ToString("yyyy-MM-dd") } })
                @Html.ValidationMessageFor(model => model.DateOfEvent, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Event Start Time*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StartTime",
                    new SelectList(ViewBag.list),
                    "Select start Time",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Event Location*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Event Type*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Type)
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    @Html.Label("Public(True)/Private(False)", htmlAttributes: new { @class = "control-label" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Event Duration(Hr)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Other Details(if any)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InvitedTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvitedTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvitedTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default btn-success" />
                <input type="submit" value="Delete" class="btn btn-default btn-danger" onclick="window.location = '@Url.Action("Delete", "Events", new { id = Model.EventId })'; return false;" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", null, null, null, new { href = Request.UrlReferrer })
</div>

BookEventManager.UserInterface/Views/Events/Index.cshtml
@model IEnumerable<BookEventManager.Shared.DTO.EventDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfEvent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OtherDetails)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InvitedTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventCreateDateTime)
        </th>
        <th>
            @Html.Label("Action")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.ActionLink(item.Title, "Details", "Events", new { id = item.EventId }, new { id = item.EventId })
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DateOfEvent)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.StartTime)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Location)
    </td>

    @if (item.Type == true)
    {
        <td>
            @Html.Label("Public")
        </td>
    }
    else
    {
        <td>
            @Html.Label("Private")
        </td>
    }
    <td>
        @Html.DisplayFor(modelItem => item.Duration)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Description)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.OtherDetails)
    </td>
    <td>
        @if (item.InvitedTo != null)
        {
            foreach (var email in item.InvitedTo.Split(','))
            {
                <label>@email</label><br>
            }
        }
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.EventCreateDateTime)
    </td>
    <td>
        @if (item.DateOfEvent >= DateTime.Now)
        {
            @Html.ActionLink("Edit", "Edit", new { id = item.EventId })
        }
    </td>
</tr>
}

</table>

BookEventManager.UserInterface/Views/Events/InvitedTo.cshtml
@model IEnumerable<BookEventManager.Shared.DTO.EventDTO>

@{
    ViewBag.Title = "InvitedTo";
}

<h2>Invited To Events</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
    </tr>
    @for (int index = 0; index < Model.Count(); index++)
    {
    <tr>
        <td>
            @Html.ActionLink(Model.ElementAt(index).Title, "Details", new { id = Model.ElementAt(index).EventId })
        </td>
    </tr>
    }

</table>